### ISSUE TITLE
Test rootpy with ROOT 6

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#101]
In ROOT 6 CINT will be replaced by cling (see http://root.cern.ch/drupal/content/way-root-6 ).
We should keep an eye on the ROOT 6 development (especially the release candidates) and try to get rootpy and root_numpy to work for the ROOT 6.0 release.

At the moment cling in ROOT trunk crashes for Python 2 and 3 on Ubuntu and Mac:

* https://savannah.cern.ch/bugs/index.php?99139
* https://savannah.cern.ch/bugs/index.php?99140
* https://savannah.cern.ch/bugs/index.php?99145

As soon as things work on Ubuntu I'll add travis-ci builds.

**Comment by cdeil** [comment]
Looks like rootpy now works with ROOT 6?
https://travis-ci.org/rootpy/rootpy
Is there something left to do here or can this issue be closed?

I guess a better long-term solution for CI and users would be to use [conda](http://conda.pydata.org/docs/) instead of building and hosting our own ROOT binaries?
Has this been discussed or is this maybe even available via some binstar channel?

**Comment by ndawe** [comment]
Good to hear from you again @cdeil! I hope you're doing well.

Yes, this issue can be closed. Re conda, I'll have a look. We now have an easy method of building ROOTs in a vagrant VM with the same env as Travis. The 3GB in a free account on Binstar would be sufficient though.
