### ISSUE TITLE
Set up Jenkins for rootpy and root_numpy Continuous Integration

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#106]
We have travis-ci, but it only runs tests for Ubuntu 32 bit.
We also want to test other Linuxes and Mac OS X.

We currently have two Macs available, one running OS X 10.4 and one 10.7, for the 10.7 machine I have virtualbox and vmware fusion installed, so we can run any number of Linuxes in virtual machines (VMs).

The current plan is to run a http://jenkins-ci.org either on the rootpy.org webserver or on the 10.7 machine, and use the others as build slaves, but if it's easier we could also run Jenkins on the 10.7 machine.

Stuff we have to figure out:
* How to set up the 10.7 machine so that it is reachable at a fixed URL
* How to run Jenkins such that it's web interface is accessible somewhere on rootpy.org
* How to manage SSH keys so that our machines remain secure.
* How to wake up, run tests and shut down VMs from Jenkins
* How to trigger Jenkins on github commits (and ideally pull requests)
* How to put the built sphinx docs from each commit on rootpy.org (but only if the build succeeded I suppose)

Any help on this is welcome, I've never done this.
We can just use this ticket to discuss the issues that come up.
I have time tomorrow and would like to get this up and running quickly.

References for myself:

* http://jenkins-ci.org
* https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin
* https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Apache
* http://root.cern.ch/drupal/content/supported-architectures
* https://wiki.jenkins-ci.org/display/JENKINS/Starting+and+Accessing+Jenkins
* https://wiki.jenkins-ci.org/display/JENKINS/Securing+Jenkins
* https://wiki.jenkins-ci.org/display/JENKINS/Apache+frontend+for+security
* http://goodliffe.blogspot.de/2011/09/how-to-set-up-jenkins-ci-on-mac.html
* https://wiki.jenkins-ci.org/display/JENKINS/Step+by+step+guide+to+set+up+master+and+slave+machines
* https://wiki.jenkins-ci.org/display/JENKINS/SSH+Slaves+plugin
* https://wiki.jenkins-ci.org/display/JENKINS/Distributed+builds

**Comment by ndawe** [comment]
Closing in favour of Travis-CI
