### ISSUE TITLE
Improve ROOT plotting in IPython notebooks

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#162]
[Here](http://nbviewer.ipython.org/4524578/) I propose to improve ROOT plotting in IPython notebooks in two ways:
* Create a `ROOT` ipython magic that creates PNG or SVG temp files and shows them inline in the notebook instead of opening an interactive X11 Window. @piti118 Possible?

I would use this e.g. for documenting some high-level analysis or write a tutorial.
* Expose the `rootpy.plotting.root2matplotlib` plotting functions directly as object methods, e.g. `hist.DrawMatplotlib()` (or some better, shorter name). This is a cosmetic improvement for something that is already possible now.

I guess there could be other things we can add as options to the `%ROOT` ipython magic, e.g.  listing all ROOT objects or the currently open file and directory or ... ?
Note that e.g. [Sherpa](http://cxc.cfa.harvard.edu/sherpa/) modified the IPython shell a bit instead of creating a new separate shell for interactive work like we now have with `roosh`.

**Comment by ndawe** [comment]
Closing this old issue. rootpy shows canvases/histograms/etc as inline images in ipython.
