### ISSUE TITLE
Conversion of ROOT trees and histograms to / from FITS format

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#27]
Gamma-ray astronomers [1, 2] and I think also [3, 4, 5] and others internally store event lists in ROOT TTrees and images and spectra and instrument responses in ROOT histograms (1D, 2D, 3D).

Often internally ROOT is used, but then because it not used by other astronomers, data is exported to FITS format [6].
A FITS file is a collection of header-data units (HDUs), each one being either an n-dimensional array or a table, so it is possible to to convert simple TTrees to FITS tables and ROOT histograms to FITS arrays.

There once was the astroroot project [7], but it has been dead for many years. I think rootpy would be the right place for easy and efficient ROOT <-> FITS conversion. Basically ROOT TTree <-> numpy array is in place already (although I didn't check if it is efficient yet) and ROOT histogram <-> numpy array could probably easily be added (make a separate ticket?). So what I plan to do is  add wrappers around these ROOT <-> numpy conversion functions that do FITS I/O via the AstroPy package [8], which would become an optional dependency of rootpy, just as PyTables is an optional dependency for HDF5 I/O at the moment.

[1] http://www.mpi-hd.mpg.de/hfm/HESS/
[2] http://www.cta-observatory.org/
[3] http://fermi.gsfc.nasa.gov/
[4] http://veritas.sao.arizona.edu/
[5] http://magic.mppmu.mpg.de/
[6] http://en.wikipedia.org/wiki/FITS
[7] http://www.isdc.unige.ch/astroroot/index
[8] http://www.astropy.org/

**Comment by cdeil** [comment]
The tree <-> numpy array converters have been improved and hist <-> numpy array converters added in the past years:
http://rootpy.github.io/root_numpy/reference/index.html#module-root_numpy

And the idea to couple rootpy or root_numpy to the FITS file format or Astropy was a bad idea.
Better to communicate via Numpy arrays.

So I'm closing this old issue ... all done.

**Comment by ndawe** [comment]
Thanks for closing this.
