### ISSUE TITLE
iPython and rootpy (tab completion, dumping information)

### ISSUE THREAD

**Issue by kratsg** [rootpy/rootpy#621]
Not sure what's going on here. I've got a file you can pull to test against (an example file generated as an output of an xAOD).

Start iPython
```
ipython qtconsole
```

and then run the following
```
from rootpy.io import root_open
f = root_open("data.root")
f.ls()
```

Notice that the output of `f.ls()` dumps to the terminal instead of in the qtconsole. Part of me thinks that's an issue with the `stdout` / `stderr` being redirected incorrectly. The other thing is that we don't seem to offer tab completion for any of the objects located within the file. Even when you access at least one of the objects, it doesn't "remember" so we might need to implement some `%ROOT` magic here.

**Comment by kratsg** [comment]
http://stackoverflow.com/questions/21541238/get-ipython-doesnt-work-in-a-startup-script-for-ipython-ipython-notebook

I found this -- might be possible workaround for redirecting output at least. I'll be using it in some of my python macros.

**Comment by ndawe** [comment]
This will probably lie within the scope of ROOTaaS

**Comment by kratsg** [comment]
I don't think this will get used since JuPyter is now being used majorly for ROOT.
