### ISSUE TITLE
Support for array in create_branches ?

### ISSUE THREAD

**Issue by alexAubin** [rootpy/rootpy#623]
Dear rootpy devs,

I'm starting to use rootpy and found the `create_branches` syntax described [here](http://www.rootpy.org/modules/trees.html#trees) very convenient. However I'm wondering if it's possible to create branch arrays, such as : 

```
tree.create_branches(
    { 'n'      : 'I',
      'tab[n]' : 'F'})
```

I naively tried it but it doesn't seems to work. Is this by any chance planned ?

Cheers,

Alex

**Comment by ndawe** [comment]
This is already possible for fixed-length arrays. But with rootpy put the array syntax after the type character:

```python
tree.create_branches(
    { 'n'      : 'I',
      'tab' : 'F[3]'})
```

This is not possible yet (variable length depending on value of another branch):

```python
tree.create_branches(
    { 'n'      : 'I',
      'tab' : 'F[n]'})
```

Better to use STL containers for now:

```python
tree.create_branches(
    { 'n'      : 'I',
      'tab' : 'vector<float>'})
```

**Comment by ndawe** [comment]
The alternate way of easily constructing trees in rootpy is with TreeModels:

http://www.rootpy.org/auto_examples/tree/model_simple.html

The nice thing about using TreeModels is that you can construct complex trees by defining a model that inherits from many simple TreeModels.

http://www.rootpy.org/auto_examples/tree/model_hierarchy.html

**Comment by ndawe** [comment]
In the end a TreeModel calls `create_branches`, but it takes care of generating all the strings, etc. understood by ``TTree::Branch``.

**Comment by alexAubin** [comment]
Okay, thanks a lot !
