### ISSUE TITLE
Drawing histogram as a line

### ISSUE THREAD

**Issue by kreczko** [rootpy/rootpy#627]
I am currently trying to think of ways to implement the 'drawing a histogram as a line' functionality to produce plots like these:
![Image of target](https://twiki.cern.ch/twiki/pub/CMSPublic/PhysicsResultsTOP11013/combined_Cross_Leptons_Pt_log.png)

I have a current example that uses root2matplotlib:
![Image of current](https://raw.githubusercontent.com/BristolTopGroup/DailyPythonScripts/master/examples/plots/Bin_Centers.png)
with code available here: https://github.com/BristolTopGroup/DailyPythonScripts/blob/master/examples/Bin_Centers.py

I was unable to find a way in the current implementation so I wanted to talk about a possible solution in order to make a pull request.

My current solution involves the use of pyplot.plot:
```python
#finebinned is the finebinned histogram shown above
y = list(h_truth_finebinned.y())
bin_edges = np.array(list(h_truth_finebinned.xedges()))
bincenters = 0.5*(bin_edges[1:]+bin_edges[:-1])
# ...
plt.plot(bincenters, y, '-')
```

While it works, I don't think it is the best solution. Any ideas?
How would this be ported to root2matplotlib?
Would it be enough to introduce a ```asline``` parameter to the ```root2matplotlib.hist``` function?

**Comment by srstevenson** [comment]
@kreczko doesn't `root2matplotlib.step` do that, or have I misunderstood?

```python
from rootpy.plotting import Hist, root2matplotlib

h = Hist(10, 0, 1)
h.FillRandom('gaus')
root2matplotlib.step(h)
```

![figure_1](https://cloud.githubusercontent.com/assets/5845679/6269158/574a8b54-b849-11e4-989c-a1003aacb110.png)

**Comment by kreczko** [comment]
@srstevenson : What I am looking for is something like the POWHEG graph in my first example.
So I want to transfer my own example (2nd plot) to:
![bin_centers](https://cloud.githubusercontent.com/assets/1213276/6269390/c7122fe0-b84a-11e4-82a3-f46d31317b23.png)

The difference is that instead of 'step' you get a smooth line going through the bin-centres

**Comment by srstevenson** [comment]
Ah I see now, I thought your second plot was the end result you wanted.

**Comment by ndawe** [comment]
That really isn't a histogram then, is it? You could convert your histogram into a graph and then draw that.

**Comment by ndawe** [comment]
I don't think an ``asline`` argument added to ``root2matplotlib.hist`` would be wise (implemented as you want it) since then it really isn't drawing a histogram. The step function draws the outline of the histogram. Otherwise use matplotlib's plot function to plot an arbitrary array of points.

**Comment by kreczko** [comment]
@ndawe thanks for the comment. So this is something that should be kept external to roopty if I understand correctly.
I will try the graph option and then tidy up the example. Maybe instead of providing this functionality for root2matplotlib (quite specific) could I provide an example for rootpy?

**Comment by ndawe** [comment]
Sure, an example would be great.

I suppose there is room for a simple ``root2matplotlib.plot`` function for plotting graphs while using the ROOT style attributes as defaults for matplotlib. ``root2matplotlib.errorbar`` can already do this, and turning off the error bars is possible with ``xerr=False`` and ``yerr=False``.

**Comment by ndawe** [comment]
Closing this for now...
