### ISSUE TITLE
Provide ROOT / rootpy Conda packages on binstar

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#642]
As mentioned in  https://github.com/rootpy/rootpy/issues/101#issuecomment-105322258, it would be great to be able to install ROOT and rootpy for continuous integration and for end-users simply with `conda install rootpy` using [conda](http://conda.pydata.org/).

There is a conda recipe for ROOT here, but I haven't tried it:
https://github.com/conda/conda-recipes/blob/master/root/meta.yaml

There's a few Linux ROOT binaries on binstar:
https://binstar.org/search?q=root

I think I remember some HEP or LSST repo on Github where they had a larger effort to provide ROOT and many other things as conda packages. Now I can't find it any more, with Google I only came across this:
https://groups.google.com/a/continuum.io/forum/#!msg/conda/LeL0rVORJO4/J4HmOTTLpwYJ
https://github.com/HEP-SF/packaging/pull/3/files?short_path=2ea39cf

@ndawe Maybe you know someone at CERN you could ask if there is some official ROOT conda distribution or if it's planned. It would be nice if we don't have to maintain this.

**Comment by kreczko** [comment]
Just had some time to test conda.
I am impressed. I got python 3, cmake 3 and gcc 4.8 working on SL 6 within 5 min (compared to O(hours) with rpms).
If I can get ROOT and rootpy the same way, then I can bundle our analysis software as well.

As for the ROOT part: maybe it is worth asking it during one of the ROOT developer meetings?
Next one is on the 10th of June: http://indico.cern.ch/event/385444/

**Comment by remenska** [comment]
I have been fiddling around with getting stable ROOT5/6 binaries to work through conda, with Python 2/3 support. The most painful thing is the ABI (binary) compatibility between different gcc(libstdc++)/glibc library versions, on various linux distributions.

Typically ROOT would even complain when the GCC headers are not of the same version as the one used for building it, so shipping the full GCC as a run dependency together with ROOT, seems like the best solution.

The recipes are available here:
https://github.com/remenska/conda-recipes

The binaries were built on a Scientific Linux 6.7 (Carbon). The default GCC (4.4.7) is too old for ROOT6, so I used the [Developer Toolset (v2) from CERN](http://linux.web.cern.ch/linux/devtoolset).
(provides everything you need to rebuild from the recipes: gcc/binutils/git/etc..):
I have tested things on: Ubuntu 11.10, 12.04, 14.04, 15.04, SLC-6.7, SLC-7. Please try it out and let me know if you experience problems. 
```
$ conda config --add channels https://conda.binstar.org/NLeSC
$ conda create --name=testenv root=6 python=3
$ source activate testenv
$ root -b -q
$ source {PATH_TO_YOUR_ANACONDA_DIR}/envs/testenv/bin/thisroot.sh
$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> f = ROOT.TFile.Open("test.root","recreate")
```

If you have other channels in your conda configuration (besides the defaults one), make sure that the following packages are picked up from the right one (NLeSC) when you create the new environment.
```
....
    gcc:        4.8.2-20               https://conda.binstar.org/NLeSC/linux-64/
    readline:   6.2.5-11               https://conda.binstar.org/NLeSC/linux-64/
....
```
ROOT is dynamically linked against glibc. If you experience errors like the following:

``` root: /lib64/libc.so.6: version `GLIBC_2.{some_old_version}' not found 
(required by /anaconda/envs/testenv100/bin/../lib/libstdc++.so.6) ```

this means that you deployed ROOT on a machine with a very old glibc version, and you need to upgrade your distro. 

So far only there is only support for Linux 64bit. OSX is uncharted territory for me, and any help would be appreciated.
Thanks a lot!

**Comment by cdeil** [comment]
@remenska – That's awesome, thank you!
:tada: 

@ndawe – Should these binaries be used for rootpy testing on travis-ci (either exclusively or in addition to what's there now)?

**Comment by remenska** [comment]
You're very welcome.
Porting root_numpy/rootpy to binstar seemed straightforward, you can also test it:
(assuming you are in the testenv environment already)
``` 
conda install rootpy
```
This should pick up the correct version of root_numpy also. Or install everything when already preparing the new environment (root=[5|6] python=[2|3]) in Conda:

```
conda create --name=testenv root=6 python=3 rootpy 
```

I only did simple rootpy I/O tests, it seems at least that works like it should. ;)

**Comment by kreczko** [comment]
@remenska : nice work. Following the conversation in the HSF packaging forum (https://groups.google.com/forum/#!topic/hep-sf-packaging-wg/h4HWHnVkBA8)

Will advertise this to our groups.

**Comment by kreczko** [comment]
BTW, it seems the recipe is now
```bash
conda install -c https://conda.anaconda.org/nlesc root rootpy
```
with `root_numpy` and `root_pandas` also available.
Full list:
https://conda.anaconda.org/NLeSC

**Comment by remenska** [comment]
Yep, thanks @kreczko!  
Btw installing rootpy alone, should already pickup the dependencies like root-numpy and root.

**Comment by kreczko** [comment]
Ah, yes, absolutely @remenska . I think I tried the other way around and wondered why rootpy is not a dependency of ROOT ;).
Is it safe to assume that you are involved in the NLeSC channel (since you were the first one I know to add a ROOT recipe)? If yes, is there a good way to report issues (e.g. root 6.06 seems to be available since 22.01.2016, but only 6.04 gets installed from the channel)? (sry for the bit of off-topic)

**Comment by remenska** [comment]
@kreczko I am the one closely involved in the NLeSC channel on Anaconda, you are right.

You can report issues here:
https://github.com/remenska/root-conda-recipes/issues

Have a look in the closed section, there is one on root 6.06 ;)
(basically it's in the dev channel and you have to be explicit when installing from non-default "main" one)
This is until I find time to properly test it.

**Comment by kreczko** [comment]
Seems this issue made it into a presentation :)
https://indico.cern.ch/event/394780/contribution/3/attachments/1239230/1821393/GDBMarch_remenska.pdf

**Comment by remenska** [comment]
@kreczko I hope you don't mind the screenshot I used for the presentation (a little bragging on the small deliverable), and thanks for the nice words! :)

**Comment by kreczko** [comment]
@remenska Do not mind at all. Was a nice surprise. 
And of course, nice words since credit where it is due :)

**Comment by cdeil** [comment]
@remenska or anyone -- could you please mention available ROOT or rootpy conda packages on
http://www.rootpy.org/install.html
?

It would be more convenient than having to find this GH issue to see where it's available.
Also -- would it be worth adding travis-ci builds for rootpy with ROOT from conda, to make sure it keeps working?

**Comment by remenska** [comment]
> Also -- would it be worth adding travis-ci builds for rootpy with ROOT from conda, to make sure it keeps working?

@cdeil What do you mean? As far as I see, rootpy Travis *is* configured with ROOT from conda.
