### ISSUE TITLE
How to cite rootpy?

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#651]
I'm writing a proceeding contribution at the moment where I mention rootpy.
As far as I know there's no paper one could cite, so I'll use the URL `rootpy.org`.

@ndawe - Do you think it's worth the effort to write a paper or proceeding on rootpy? (or combined with PyROOT, I think there's also no paper on why PyROOT was written and how it works?)

**Comment by kreczko** [comment]
With https://zenodo.org/ you can create a DOI for rootpy and it should be citable.
Can even be done per version and automated (there is a github hook for that).

**Comment by ndawe** [comment]
I plan to upload something on the arXiv, but first for root_numpy and then potentially expand that to cover rootpy. @kreczko great idea. I'm going to generate a DOI for rootpy and root_numpy. Thanks for suggesting that.

**Comment by ndawe** [comment]
We now have a DOI for root_numpy: http://dx.doi.org/10.5281/zenodo.18750
Will get one for rootpy now too...
Pretty cool!

**Comment by ndawe** [comment]
rootpy 0.8.0 is released and has this DOI:

http://dx.doi.org/10.5281/zenodo.18897
