### ISSUE TITLE
Histogram label sizes aren't set correctly

### ISSUE THREAD

**Issue by kratsg** [rootpy/rootpy#660]
https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/style/atlas/style.py#L88-L103

The size for title and labels are set at 30, however the official `AtlasStyle.C` sets it at `0.05` [eg: 5% of the width of the canvas]. 30 would mean 3000% I believe.

```
  // use large fonts
  //Int_t font=72; // Helvetica italics
  Int_t font=42; // Helvetica
  Double_t tsize=0.05;
  atlasStyle->SetTextFont(font);

  atlasStyle->SetTextSize(tsize);
  atlasStyle->SetLabelFont(font,"x");
  atlasStyle->SetTitleFont(font,"x");
  atlasStyle->SetLabelFont(font,"y");
  atlasStyle->SetTitleFont(font,"y");
  atlasStyle->SetLabelFont(font,"z");
  atlasStyle->SetTitleFont(font,"z");
```

https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/PubComPlotStyle

**Comment by kratsg** [comment]
It looks like it's being hard-coded in terms of pixels instead. When I draw a new `Pad()` and then try to do the same thing again, it seems to revert back to percentages for those.

**Comment by kratsg** [comment]
So here's what I've found so far:

```
set_style('ATLAS')
Hist(10, 0, 1).xaxis.get_label_size()  # 30
Hist(10, 0, 1).yaxis.get_label_size()  # 30

root_open(fname).path.to.histogram.xaxis.get_label_size()  # 0.035
root_open(fname).path.to.histogram.yaxis.get_label_size()  # 0.035
```

which is very hard to realize.

**Comment by kratsg** [comment]
What makes this worse is I do the following:

```
canvas = Canvas(....)

# mc histograms
hstack = HistStack(name='foo')
map(hstack.Add, histograms)
hstack.draw()

# data histogram
data = Hist(10, 0, 1)
data.draw()

# do the ratio
canvas.set_bottom_margin(0.3)
p = Pad(...)
p.set_top_margin(0.7)
p.Draw("same")
p.cd()
ratio = Hist.divide(data, hstack.GetHistogram())
ratio.draw("elpsame")
```

The problem shows up when I decide I want to copy my label styles over. I find that the `hstack` dictates the size of the labels with `hstack.xaxis.get_label_size()` returning `30` (in pixels I presume). However, I find that doing `ratio.xaxis.set_label_size(30)` is ridiculously large, that the appropriate size is more like `0.025`. I'm not sure why there's such a discrepancy here.

**Comment by kratsg** [comment]
https://github.com/kratsg/TakeOverTheWorld/blob/master/totw.py -- here's the code I've been running. I'm still trying to figure out where it goes wrong, but I don't understand the discrepancy.

**Comment by kratsg** [comment]
Looking into this more, I see the following output:

```
(Pdb) hstack[0]
Hist('dijets:all/MET/met')
(Pdb) hstack[0].GetXaxis()
<ROOT.TAxis object ("xaxis") at 0x7f89adbb9958>
(Pdb) hstack[0].GetXaxis().GetLabelSize()
0.03500000014901161
(Pdb) hstack.xaxis
Axis('xaxis')
(Pdb) hstack.GetXaxis()
<ROOT.TAxis object ("xaxis") at 0x7f89adeba068>
(Pdb) hstack.GetXaxis().GetLabelSize()
30.0
```

It's not clear to me why the `hstack` has a different label size at all.

**Comment by ndawe** [comment]
This seems to be just the result of mixing ROOT font precisions (pixels vs relative pad ratios)
