### ISSUE TITLE
Ternary operator in tree draw expression

### ISSUE THREAD

**Issue by heroxbd** [rootpy/rootpy#669]
In the present master:

  https://github.com/rootpy/rootpy/blob/cfe3b304ca7a8b2f6622ab6698ba5798d32bf582/rootpy/tree/tree.py

The order of an expression is reversed by

    fields = re.split('(?<!:):(?!:)', exprdict['branches'])
    num_dimensions = len(fields)
    expression = ':'.join(fields[:3][::-1] + fields[3:])

This breaks an expression with a ternary operator, like "x:a?y:z"

I can't figure out a regex to count this.  Hints?

**Comment by ndawe** [comment]
Yikes. I honestly didn't think of this...

Let's see if we can cook something up.... Or maybe an option should be included to revert to the original TTree behaviour.

**Comment by heroxbd** [comment]
Yeah, or probably accepting a list as an alternative, like ["x", "a?y:z"] ?

**Comment by ndawe** [comment]
I like your idea more. Probably the cleanest way forward.

**Comment by ndawe** [comment]
Fixed in #670

**Comment by heroxbd** [comment]
Thanks a lot Noel.
