### ISSUE TITLE
Dynamically creating branches of type stl.vector

### ISSUE THREAD

**Issue by kreczko** [rootpy/rootpy#679]
Dear all,

I am currently trying to create trees with dynamic sets of branches (i.e. defined at runtime):

```
f = root_open("chaintest1.root", "recreate")

tree = Tree("test")
branches = {
     'x': 'F',
     'y': 'F',
     'z': 'F',
     'i': 'I',
     'vi': stl.vector('int')}
tree.create_branches(branches)
```

However, this fails since TreeBuffer(branches) does not accept branches of this type as it looks for string definitions:

```
 File "ntuple/tests/rootpy_test.py", line 37, in <module>
    tree.create_branches(branches)
  File "/software/miniconda/envs/ntuple/lib/python2.7/site-packages/rootpy/tree/tree.py", line 141, in create_branches
    branches = TreeBuffer(branches)
  File "/software/miniconda/envs/ntuple/lib/python2.7/site-packages/rootpy/tree/treebuffer.py", line 49, in __init__
    self.__process(branches)
  File "/software/miniconda/envs/ntuple/lib/python2.7/site-packages/rootpy/tree/treebuffer.py", line 76, in __process
    array_match = re.match(TreeBuffer.ARRAY_PATTERN, vtype)
  File "/software/miniconda/envs/ntuple/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

However, if I use a TreeModel as per example (http://www.rootpy.org/auto_examples/tree/model.html), it works. This means that the logic for what I want does exist in one way or another.

Looking through the TreeModel code the solution seems quite simple:

```
branches = {
     'x': FloatCol(),
     'y': FloatCol(),
     'z': FloatCol(),
     'i': FloatCol(),
     'vi': stl.vector('int')}
MyTreeModel = TreeModelMeta('MyTreeModel', (TreeModel,), branches)
tree = Tree("test", model = MyTreeModel)
```

where `branches` can be created in a dynamic way.

This brings me to my question:
`Tree.create_branches` currently only expects strings and `TreeBuffer.__process(branches)` does not find a match for a `stl.vector(<type>)`. Is there a particular reason for that (the code is not quite clear)?

If I was to prepare a PR to fix this issue, would I
1. change `Tree.create_branches` to use a temporary TreeModel (name probably based on a hash)?
2. change `TreeBuffer.__process(branches)` to be able to parse `stl.vector(<type>)`?
3. change `TreeBuffer.__process(branches)` not to parse complete types (`FloatCol`, `stl.vector(<type>)`, etc)?

**Comment by ndawe** [comment]
TreeBuffer.__process now handles everything TreeModel can.
