### ISSUE TITLE
rootpy to ROOT plots have no color

### ISSUE THREAD

**Issue by TKGgunter** [rootpy/rootpy#682]
Hello, I am trying to create histograms and graphs with color but no matter which method I try to use no color. Whether the class method or attribute the color does not show up on subsequent root plots.  For example I tryed the http://www.rootpy.org/auto_examples/plotting/plot_matplotlib_hist.html
example, and the root plot had no color while matplotlib did.  I am using running a ssh machine, with a conda 2.5 install of python 2.7 and rootpy 0.8.1, trhough pip. This might be an inssue with how package was installed since my mac install works just fine.

Any help would be appreciated, 
Thanks

**Comment by ndawe** [comment]
It could be an issue with the particular version of ROOT on that remote machine. No problems with the style attributes on my end and I'm using 5.34/34

**Comment by ndawe** [comment]
What version of ROOT do you have setup?

**Comment by TKGgunter** [comment]
I am using 5.32.

**Comment by ndawe** [comment]
Upgrade to a recent 5.34. Earlier releases of ROOT are hit and miss. I've reported many bugs to the ROOT dev team over the years and I especially remember certain releases of 5.32/X and 5.30/X having many issues.

**Comment by TKGgunter** [comment]
Thanks I think this is probably the issue
