### ISSUE TITLE
Not valid fill style (root2hdf5 bug)

### ISSUE THREAD

**Issue by henryiii** [rootpy/rootpy#684]
When using `root2hdf5` (script or function), I get `ValueError: 101 is not a valid fill style` when I try to convert a GEANT4 produced root file. By adding `101:None` to the dictionary in `rootpy/plotting/base.py`, I can fix the error and it converts fine. The list does contain 1001, but not 101.

Seems like rootpy should not even be touching the histograms or trying to connect to the graphical server at all when converting trees with this method.

Another fix would be to simply print a warning and continue with no fill if fill style is not recognized. I could put together a patch if helpful.

**Comment by ndawe** [comment]
Interesting. I'm surprised it is touching histograms. This can be fixed.

I've never seen fill style 101 though. They should either be 0 or four digits right?

**Comment by henryiii** [comment]
I'm using GEANT4's analysis manager, which outputs in several formats, including ROOT. This is the default setting, I don't think (due to it wrapping several output formats) that it can be changed even if I wanted a different fill style.

**Comment by henryiii** [comment]
Agreed about the value, though, I don't see it listed in the fill styles on ROOT's docs.

**Comment by ndawe** [comment]
Yeah, I think I can fix this so rootpy doesn't care. Anyway, you're right that in root2hdf5 it should not even care about histograms. I think this is all an unintentional side effect of #673

**Comment by ndawe** [comment]
Fixed in #690
