### ISSUE TITLE
chance for some visibility!

### ISSUE THREAD

**Issue by mverzett** [rootpy/rootpy#686]
Hi,

I've seen a post for this small workshop on CERN's walls http://indico.cern.ch/event/487416/ and I would really be looking forward for some presentation about rootpy. I do not feel involved enough to submit an abstract myself, but I hope one of you guys does it!

Cheers,

Mauro

**Comment by ndawe** [comment]
Thanks Mauro! I would love to. I'll submit an abstract and will try to make travel plans.

**Comment by betatim** [comment]
If you need an additional reason for coming: June 2nd and 3rd is the @mozillascience global sprint. I will be at CERN again and working on [`everware/everware`](/everware/everware).

**Comment by ndawe** [comment]
Unfortunately I'll instead be at CERN from June 7 to 17. I offered to present rootpy remotely (and submitted an abstract) but they didn't seem keen on setting up video conferencing for the workshop. So, hopefully next time? Or if you are attending, you are more than welcome to spread the word :smile:

**Comment by kreczko** [comment]
Weird..they do have a vidyo room:
http://indico.cern.ch/event/487416/other-view?view=standard

It is a bit of a shame, since there seems to be plenty of PyROOT content, rootpy would be a great fit.

**Comment by ndawe** [comment]
Yeah seeing the vidyo room made me submit an abstract anyway with a comment mentioning I could present remotely. Oh well...

**Comment by kreczko** [comment]
It seems rootpy is at least mentioned on slide 18:
https://indico.cern.ch/event/487416/contributions/2174917/attachments/1281052/1903162/ROOT-DevCERN-20160530.pdf

> Other packages such as rootpy provides a more pythonic ROOT
