### ISSUE TITLE
Proxy broken in rootpy.io.pickler:load

### ISSUE THREAD

**Issue by baxen** [rootpy/rootpy#692]
In both the latest version available with `pip` (`0.8.1` I believe) and in `0.8.2.dev0`, I can no longer use the pickler with proxies.  Here is an example:

```python
from rootpy.plotting import Hist
from rootpy.io import pickler, root_open

h = Hist(5,0,1)
h.Print("all")
with root_open('pickled.root','recreate') as outfile:
    pickler.dump([h], outfile)

# This works fine!
with root_open('pickled.root') as infile:
    print pickler.load(infile, use_proxy=0)

# DoesNotExist Error
with root_open('pickled.root') as infile:
    print pickler.load(infile, use_proxy=1)
```

The proxies are a great idea and a nice feature - it would be great to have them back.

**Comment by ndawe** [comment]
Thanks for reporting. This must be an unintentional side-effect of changed made to support python 3. I'll try to fix and add a unit test to prevent this from happening again.

**Comment by ndawe** [comment]
I can confirm that it's broken and that it did in fact work in cc6ab53f2c

**Comment by ndawe** [comment]
Fixed. Will creating a PR now and will release a new tag

**Comment by ndawe** [comment]
0.8.2 is released with this bugfix.

**Comment by baxen** [comment]
Thank you for the quick fix!
