### ISSUE TITLE
isinstance(hist, Hist)  # False ?

### ISSUE THREAD

**Issue by parnmatt** [rootpy/rootpy#698]
I just got some failing code, and I'm a little confused.

```python
>>> from rootpy import ROOT
>>> from rootpy.plotting import Hist
>>> hist = Hist(1, 0, 1)
```

It's apparently not an instance of the class I made it from
```python
>>> isinstance(hist, Hist)
False
```

However, it is an instance of the ROOT class
```python
>>> isinstance(hist, ROOT.TH1)
True
```

What's going on here?

**Comment by ndawe** [comment]
rootpy.plotting.Hist is actually a function, not a class (we are a bit sneaky there). This was the only way we could dynamically set up the appropriate ROOT base class on-the-fly. If you want to check if something is a histogram, then use ``isinstance(hist, ROOT.TH1)`` or to check if it is specifically a rootpy TH1 subclass:

```
from rootpy.plotting.hist import _HistBase
isinstance(hist, _HistBase)
```

**Comment by ndawe** [comment]
I initially tried implementing Hist with a custom metaclass, but it was not possible to use our own metaclass and inherit from ROOT's classes at the same time...

**Comment by parnmatt** [comment]
Make sense; cheers. :smile:
