### ISSUE TITLE
HistStack for histograms with different binnings

### ISSUE THREAD

**Issue by suhlatwork** [rootpy/rootpy#699]
I am trying to use histograms with different binnings in a `HistStack` and find that this is not working in `rootpy`. In principle I just want to use the histogram stack as a container of histograms so that I do not have to take care of finding the maximum and minimum for drawing by hand. In ROOT the following is valid:
```
TH1D b("b", "b", 100, 0.5, 2.5)
b.FillRandom("gaus")

TH1D c("c", "c", 100, -1.5, 1.5)
c.FillRandom("gaus")

THStack a("a", "a")
a.Add(&b)
a.Add(&c)
a.Draw("nostack")
```
Note the usage of the `nostack` drawing option, if this is not used, then also ROOT will fail with a similar error as described below. To my understanding the equivalent in `rootpy` should be
```
import rootpy.plotting

b = rootpy.plotting.Hist(100, 0.5, 2.5)
b.FillRandom("gaus")

c = rootpy.plotting.Hist(100, -1.5, 1.5)
c.FillRandom("gaus")

a = rootpy.plotting.HistStack()
a.Add(b)
a.Add(c)
```
But adding the second histogram results in the following errors:
```
INFO:ROOT.TH1F.Add] Attempt to add histograms with different axis limits - trying to use TH1::Merge
ERROR:ROOT.TH1F.Merge] Cannot merge histograms - limits are inconsistent:
 first: (100, 0.500000, 2.500000), second: (100, -1.500000, 1.500000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...../lib/python2.7/site-packages/rootpy/plotting/hist.py", line 2419, in Add
    self.sum += hist
  File "...../lib/python2.7/site-packages/rootpy/plotting/hist.py", line 1082, in __iadd__
    self.Add(other)
  File "...../lib/python2.7/site-packages/rootpy/plotting/hist.py", line 1082, in __iadd__
    self.Add(other)
  File "...../lib/python2.7/site-packages/rootpy/logger/magic.py", line 247, in intercept_next_line
    raise exception
rootpy.ROOTError: level=3000, loc='TH1F::Merge', msg='Cannot merge histograms - limits are inconsistent:
 first: (100, 0.500000, 2.500000), second: (100, -1.500000, 1.500000)'
```
Is it possible to somehow use histograms with different binnings in a `HistStack`, or would this be a feature that still needs to be added.

**Comment by ndawe** [comment]
Hmm. This is due to HistStack keeping track of a running sum of the histograms to compute the min and max of the stack (assuming it's always stacked). Instead we can just compute the min/max based on the sum if a new argument stacked is True and otherwise take the max/min of all histogram maxima/minima.

**Comment by ndawe** [comment]
Fixed in #700. Once merged do this:

```
stack = HistStack([a, b], stacked=False)
```

**Comment by suhlatwork** [comment]
Thank you for the quick fix!

Unfortunately the `Clone` method does not pass the status of `stacked` to the clone. Could you please add this?

**Comment by ndawe** [comment]
Oops. Done now in #701
