### ISSUE TITLE
Using a Branch as a tree

### ISSUE THREAD

**Issue by JOliver-GH** [rootpy/rootpy#704]
Hi, I have a prepared NTuple from a digitization-reconstruction recipe. In this NTuple I have a list of trees, and in those trees I have branches. 

I have code where I do the following: 

signal=root_open(signalMC_location + "/" +signalfilename)
treesSR = signal.trees_SR_

and its working brilliantly. 

How can I change the "treesSR" to be a branch, instead of a tree? 

for example described here in pseduocode: 

signal=root_open(signalMC_location + "/" +signalfilename)

treesSR = signal.Tree.Branch 

I know this should be simple enough I just can't think how to solve it! 

Cheers 

Jason

**Comment by ndawe** [comment]
Hi Jason,

You can use tree.GetBranch("branchname") to access the TBranch, just like in plain PyROOT. But in rootpy it's even easier to deal with the branches from within your event loop because rootpy automatically sets up the memory buffers for the branch values at that stage:

```python
for entry in tree:
    print tree.branchname
```

or 

```python
for entry in tree:
    print entry.branchname
```

(entry is just a reference to the tree)

That doesn't give you the branch but rather the value stored in the branch for that entry in the tree

**Comment by JOliver-GH** [comment]
Ahh thanks, 

now if i had a tree, with a subtree, with a variable in that, 

Tree
    SubTree
        variable1
        variable2

how would I "Draw" it in the same way that I use Tree->Draw(variable,"","")

for instance 

SubTree->Draw("variable1","","")

Cheers,

**Comment by ndawe** [comment]
By subtree do you mean a tree within a directory of your ROOT file?

**Comment by JOliver-GH** [comment]
So this is the variable I am looking to Draw, but SCT_Clusters is the "Tree" I want to access

![variablechoice](https://cloud.githubusercontent.com/assets/17489193/17954771/5ec513dc-6abc-11e6-9157-225ebfdcc1b3.png)

**Comment by ndawe** [comment]
That's a leaf of the SCT_Clusters branch in the tree CollectionTree. Can you try ``file.CollectionTree.Draw('SCT_Clusters.@size')`` ?

**Comment by JOliver-GH** [comment]
I tried this with the same file and I get the following:

[cid:ECDEF709-6262-442B-B1C1-52D6C95140D5@ad.adelaide.edu.au]

using this file:

[cid:071F3516-3AB1-4FB3-A1A6-632CBEE22FD7@ad.adelaide.edu.au]

When I plot it in the TBrowser I have the following:

[cid:2B2244A8-E38C-4124-9F49-06D9EB697A63@ad.adelaide.edu.au]

Hope this helps in solving the problem!

-JO
On 25 Aug 2016, at 1:34 PM, Noel Dawe <notifications@github.com<mailto:notifications@github.com>> wrote:

file.CollectionTree.Draw('SCT_Clusters.@size')

**Comment by JOliver-GH** [comment]
sorry, and if you want to see the relevant segment of the code I’ve wrote here it is , sorry about the comments,

[cid:F00181A6-8824-4601-B7C0-BEA3AE1C66B7@ad.adelaide.edu.au]
On 25 Aug 2016, at 2:20 PM, Jason Oliver <jason-oliver@live.com<mailto:jason-oliver@live.com>> wrote:

I tried this with the same file and I get the following:

<PastedGraphic-1.tiff>

using this file:

<PastedGraphic-2.tiff>

When I plot it in the TBrowser I have the following:

<Screen Shot 2016-08-25 at 2.18.12 PM.png>

Hope this helps in solving the problem!

-JO
On 25 Aug 2016, at 1:34 PM, Noel Dawe <notifications@github.com<mailto:notifications@github.com>> wrote:

file.CollectionTree.Draw('SCT_Clusters.@size')

**Comment by ndawe** [comment]
I can't see the images...

**Comment by JOliver-GH** [comment]
Sorry!! I've gone back and editted them back in!

**Comment by ndawe** [comment]
Closing this since it is more of a ROOT question that should be discussed on the ROOT forum.
