### ISSUE TITLE
raw_input() --> input() in `rootwait.py`

### ISSUE THREAD

**Issue by xaratustrah** [rootpy/rootpy#708]
First of all thanks for the great job! I have successfully installed root, PyROOT and **rootpy** and everything works fine, except one small error in file `rootwait.py` in function `wait_failover` there seems to be a usage of `raw_input()` which is deprecated. I changed it manually to `input()` and then everything was fine. 

root v. 6.06/08 +python34 from macports on OSX 10.11.6 El Capitan
rootpy 0.8.3 by PIP

**Comment by ndawe** [comment]
Thanks! Fixed in #709

**Comment by xaratustrah** [comment]
cool thanks.

**Comment by ndawe** [comment]
By the way, python 3 isn't even officially supported by ROOT yet: https://sft.its.cern.ch/jira/browse/ROOT-7640

**Comment by xaratustrah** [comment]
True, but in fact I am trying to use **rootpy** for my analysis in python 3.4 anyway, and I am looking forward to full python 3 support someday. Up to now relative good success has been achieved. Here and there sometimes the plots freeze but things are going on. If I go through the example directory of **rootpy** and try to run the plots some will work, but some will complain about errors that are quite similar. So maybe it is rather easy to fix them, at least those related to **rootpy** not PyROOT.
My current configuration is:

```
Python 3.4.5 +readline from macports
root v. 6.06/08 +python34 from Macports on OSX 10.11.6 El Capitan
ndawe/rootpy from GH
```

Here is a small report:


I always get this warning, no matter what I plot:

`WARNING:rootpy.interactive.rootwait] wait_for_zero_canvases is failing over to input()`

Other than that:

Example: **plot_autobinning.py**

Works


Example: **plot_bin_merging.py**


```
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ROOT.py", line 303, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named 'root_numpy'
```



Example **plot_hist.py**

Works


Example **plot_matplotlib_graph.py**


```
File "/Users/shahab/Documents/Work_Directories/git/rootpy/rootpy/plotting/style/__init__.py", line 76, in set_style
    for k, v in style_dictionary.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

Example **plot_matplotlib_hist.py**
```
File "/Users/shahab/Documents/Work_Directories/git/rootpy/rootpy/plotting/style/__init__.py", line 76, in set_style
    for k, v in style_dictionary.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
Example **plot_matplotlib_hist2d.py**


```
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ROOT.py", line 303, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named 'root_numpy'
```

Example **plot_overlay.py**

Works


Example **plot_style.py**

Works
