### ISSUE TITLE
Overflow bins (seemingly) inconsistently treated in x and y directions

### ISSUE THREAD

**Issue by gbesjes** [rootpy/rootpy#712]
It seems that overflow handling in 2D histograms is treated differently in the x and in the y direction: 

    >>> h2 = Hist2D(10, 0, 100, [0, 10, 20], name="dummy")
    >>> h2.Fill(10, 30)
    38
    >>> h2.overflow()
    [0.0, 0.0, 0.0, 0.0]
    >>> h2.Fill(110, 5)
    23
    >>> h2.overflow()
    [0.0, 1.0, 0.0, 0.0]
    >>> h2.Fill(110, 15)
    35
    >>> h2.overflow()
    [0.0, 1.0, 1.0, 0.0]
    >>> h2.Fill(110, 25)
    47
    >>> h2.overflow()
    [0.0, 1.0, 1.0, 1.0]
    >>> h2.Fill(110, -25)
    11
    >>> h2.overflow()
    [1.0, 1.0, 1.0, 1.0]

Is this expected behaviour? The docs state:
> Depending on the dimension of the histogram, may return an array.

I'd have expected in this scenario that there would be 2 overflow bins in the x-direction (since there are 2 bins in y) and 10 in the y-direction (since there are 10 bins in x), plus a single bin if both x *and* y fall outside of the range of the histogram. 

It now looks like there are only 4 overflow bins to the right of 100, and 4 underflow bins to the left of 0. 

If this is indeed expected behaviour, it would be great if it could be documented.

**Comment by gbesjes** [comment]
Closing this issue as it's hidden in the "axis" option, which takes integers and not strings. Sorry for the noise.

**Comment by ndawe** [comment]
Ah, relief! I was just looking at this. Thanks.
