### ISSUE TITLE
Documentation issue for merging overflow bins

### ISSUE THREAD

**Issue by gbesjes** [rootpy/rootpy#713]
Hi, 

This time not something where I didn't read the docs carefully enough :)

The documentation states that there's an easy trick to use merge_bins to merge the overflow and the last real bin: 

> newhist = hist.merge_bins([(0, 1), (-2, -1)])

However, it doesn't seem to work as one would expect. First, let's start with a non-uniform binning:

    >>> h = Hist([0, 10, 20, 50], name="dummy")
    >>> h.Fill(60)
    4
    >>> newhist = h.merge_bins([(0, 1), (-2, -1)])
    >>> newhist.GetBinContent(0)
    0.0
    >>> newhist.GetBinContent(1)
    1.0
    >>> newhist.GetBinContent(2)
    0.0
    >>> newhist.GetBinContent(3)
    0.0
    >>> newhist.GetBinContent(4)
    0.0

Using this kind of functionality:
    h[h.nbins()] = h[h.nbins()].value + h.overflow()
    h[h.nbins()+1] = 0

Would put it in the correct bin number. 

It is not an issue due to the binning. If I'd do the same with a 10-bin histogram:

    >>> h = Hist(10, 0, 10, name="dummy")
    >>> h.Fill(60)
    11
    >>> newhist = h.merge_bins([(0, 1), (-2, -1)])
    >>> newhist.Draw()
    >>> newhist.GetBinContent(1)
    0.0
    >>> newhist.GetBinContent(2)
    0.0
    >>> newhist.GetBinContent(3)
    0.0
    >>> newhist.GetBinContent(4)
    0.0
    >>> newhist.GetBinContent(5)
    0.0
    >>> newhist.GetBinContent(6)
    0.0
    >>> newhist.GetBinContent(7)
    0.0
    >>> newhist.GetBinContent(8)
    1.0
    >>> newhist.GetBinContent(9)
    0.0
    >>> newhist.GetBinContent(10)
    0.0

This is a bit surprising. Either the merge_bins() function does something different, or the indexing is wrong. However, that last functionality seems to behave OK:

    >>> h.Fill(60)
    11
    >>> h[-2].value
    0.0
    >>> h[-1].value
    1.0
    >>> h[h.nbins()].value
    0.0
    >>> h[h.nbins()+1].value
    1.0

Is the piece in the docs perhaps a holdover from when the overflow bins were still indexed differently? 

In general, for 1D histograms, a member function like this might be a quite handy addition (now still written as non-member; it's my own utility function):

    def mergeOverflow(h):
        h[h.nbins()] = h[h.nbins()].value + h.overflow()
        h[h.nbins()+1] = 0

**Comment by ndawe** [comment]
Yikes something is broken!

**Comment by ndawe** [comment]
This *did* work. I'm wondering what changed on the ROOT side that would break this.

**Comment by ndawe** [comment]
Found the bug I think. Will be fixed soon.

**Comment by gbesjes** [comment]
In the meantime, I wrote a quick fix for this and to support this for 2-dimensional histograms on a range of bins as well. (The extension is wrong as it's not possible to upload .py files.) Feel free to use if it useful in any way or to disregard it. 

[overflow.txt](https://github.com/rootpy/rootpy/files/566671/overflow.txt)

**Comment by ndawe** [comment]
This works:
```
a.merge_bins([(0, 1)]).merge_bins([(-2, -1)])
```
The bug is related to two bin windows referring to overflow bins in the same merging list

**Comment by ndawe** [comment]
Wow, it was just a missing copy. In the block of code that checks for overlapping index ranges it was unintentionally altering a list inplace instead of a copy of it. Will commit and merge...

**Comment by ndawe** [comment]
This clearly needs some unit test coverage so I'll add that too...

**Comment by ndawe** [comment]
Should be fixed by #716
