### ISSUE TITLE
BinProxy.value type does not match underlying type

### ISSUE THREAD

**Issue by gbesjes** [rootpy/rootpy#714]
A BinProxy.value does not yield the same type as the original underlying type:

    >>> from rootpy.plotting import Hist2D
    >>> h2 = Hist2D(2, 0, 10, 10, 0, 20, name="2D", type="I")
    >>> h2.Fill(3, 25)
    >>> h2.Fill(3, 25)
    >>> h2.Fill(7, 25)
    >>> print type(h2[1, h2.nbins(axis=1)+1].value)
    <type 'float'>

This should have been an int. 

In addition, it would be nice if not only type="I" but also type=int would be supported as an argument - it seems more pythonic (and matches what e.g. argparse does).

**Comment by ndawe** [comment]
This is because TH1.GetBinContent is always a double. Would have been better if ROOT used template classes here... Their new interface will be templated AFAIK.

**Comment by ndawe** [comment]
TH1D, etc don't override GetBinContent

**Comment by gbesjes** [comment]
Is a BinProxy aware of what sort of histogram it came from? If so, a cast could perhaps be implemented. If not it's just one of these sucky things that ROOT does to us I guess... :)

**Comment by ndawe** [comment]
It's connected to the histogram with self.hist, so it could be aware of the type and cast if necessary.

**Comment by gbesjes** [comment]
It's not strictly needed, but would be a nice (although minor) improvement. I ran into this in designing some asserts for another piece of code.

**Comment by ndawe** [comment]
The casting will just add (normally) unnecessary overhead so I'd prefer that we don't. Better that ROOT handles returning the proper data type but that will most likely have to wait for large changes in ROOT 7.
