### ISSUE TITLE
TypeError: unhashable type: 'TF1'

### ISSUE THREAD

**Issue by bashokam** [rootpy/rootpy#715]
When doing a ROOT fit via:
gfit = ROOT.TF1("Total","expo",0, 100)
and trying to:
gfit.Draw("E4ALsame")

I get the error:
`/home/user/.local/lib/python3.4/site-packages/rootpy-0.8.3.dev0-py3.4.egg/rootpy/plotting/__init__.py` in Draw(self, *args, **kwargs)
     41 class DrawableKeepAlive(object):
     42     def Draw(self, *args, **kwargs):
---> 43         keepalive(ROOT.gPad.func(), self)
     44         return super(DrawableKeepAlive, self).Draw(*args, **kwargs)

/home/user/.local/lib/python3.4/site-packages/rootpy-0.8.3.dev0-py3.4.egg/rootpy/memory/keepalive.py in keepalive(nurse, *patients)
     30         # PyROOT missing __hash__ for Python 3
     31         nurse.__class__.__hash__ = object.__hash__
---> 32     KEEPALIVE.setdefault(nurse, set()).update(patients)

TypeError: unhashable type: 'TF1'
`
Environment:
Python 3.4
latest rootpy: rootpy                    0.8.3.dev0
root                      6.04             py3.4_gcc4.8.2    NLeSC

**Comment by ndawe** [comment]
Right, this is because ``__hash__`` is not implemented by default in python 3 if ``__eq__`` is defined. Need some workaround here...

**Comment by ndawe** [comment]
Are you using rootpy.ROOT there for ROOT.TF1("Total","expo",0, 100)?

**Comment by ndawe** [comment]
Try the following:

```
from rootpy.plotting import F1
gfit = F1("expo",0, 100, name="Total")
...
gfit.Draw("E4ALsame")
```

rootpy should be patching in a ``__hash__``. Best not to mix bare PyROOT and rootpy, such as drawing TF1 instead of F1 (inherits from TF1) onto a Canvas (inherits from TCanvas) instead of TCanvas

**Comment by bashokam** [comment]
Yes used ROOT.TF1.
Changed it to F1. That works. Thanks.

**Comment by ndawe** [comment]
With #717 this should no longer happen if you mix and match PyROOT and rootpy. In that case the keepalive mechanism will just ignore the request but show a warning.
