### ISSUE TITLE
Update docs to version 0.9

### ISSUE THREAD

**Issue by cdeil** [rootpy/rootpy#730]
@ndawe - The docs at http://www.rootpy.org/ are currently for v0.8.3 and https://github.com/rootpy/rootpy/blob/master/WHATSNEW.md has v0.8 as latest entry.

I see you released https://pypi.python.org/pypi/rootpy/0.9.0 a week ago and this is what I have installed.

Can you please update the docs? I mean ideally we'd use readthedocs where there can be multiple versions, no? I've set this up for http://docs.gammapy.org and many other projects do the same. RTD now supports conda install, so getting the rootpy docs build running there shouldn't be too hard?

Should we include the "what's new" in the docs, so that people (like me) can find it?

**Comment by henryiii** [comment]
I'd also like to see the tags turned into releases with notes, since I'm now following https://github.com/rootpy/rootpy/releases.atom and that's a good way to see what's new. (Besides being a good way to follow releases from many packages, but just the tags does that).

**Comment by ndawe** [comment]
@henryiii do you have some free time to write the release notes?

**Comment by henryiii** [comment]
@ndawe I might be able to help later in the week. What's been done so far?
