### ISSUE TITLE
Byteplay doesn't work with Python 3.6

### ISSUE THREAD

**Issue by beojan** [rootpy/rootpy#733]
Now the error is:
```
---> 76 hascode = {MAKE_FUNCTION, MAKE_CLOSURE}
     77
     78 if version_info.minor > 2:

NameError: name MAKE_CLOSURE is not defined
```

**Comment by rprechelt** [comment]
Any update on this? Byteplay has a commit as of March 12 that claims Python3.6 support (see TravisCI log [here](https://travis-ci.org/serprex/byteplay/jobs/210274909)). Can rootpy be updated to use the latest commit of byteplay to support Python3.6/3.5?

**Comment by ndawe** [comment]
This is awesome news. I feared having to rewrite this component in rootpy to avoid the need for byteplay completely. I'll try the updated byteplay.

**Comment by ndawe** [comment]
Closing this as it's now working after #745
