### ISSUE TITLE
TreeChain iteration fails after reset

### ISSUE THREAD

**Issue by nwoods** [rootpy/rootpy#735]
[This line](https://github.com/rootpy/rootpy/blob/master/rootpy/tree/chain.py#L146) fails because the current tree has been set to None.

**Comment by Awen0121** [comment]
I have the same problem as well.
Also, it seems the behaviour when using TreeChain.GetEntries/TreeChain.GetEntriesFast is very different from using TChain.GetEntries/TChain.GetEntriesFast.
I think it only returns the total entries for that single file is read now.

**Comment by ndawe** [comment]
Fixing this.

@Awen0121 right, it calls methods on the current tree that aren't overridden on TreeChain. I'll add GetEntries etc. Also note that len(chain) is the number of files in chain, not the total number of entries.

**Comment by ndawe** [comment]
Fixed in #750 and added tests. TreeChain.GetEntrues[Fast] also gives you the total number of entries in all files (internally uses a TChain and calls GetEntries on that).
