### ISSUE TITLE
Autocomplete branches question

### ISSUE THREAD

**Issue by henryiii** [rootpy/rootpy#737]
I've been working with a little helper class that makes trees much easier to work with in an interactive environment, and makes cuts on branches more pythonic; I was wondering if you'd be interested in accepting something like that in RootPy? Here's what it currently looks like (the current interface is a separate class `TextTree` at the moment, but would be turned into a property on a rootpy tree if this is useful):

The following assumes it would be a property called `b`, short for branches.

```python
dir(tree.b) # Shows the branches, works with tab completion, too
['oneBranch','twoBranch']
tree.Draw(tree.b.oneBranch, tree.b.twoBranch < 1.2)
```

In order to not pollute the namespace of `Tree`, it is a property (`b` here). A branch is basically equivalent to the string representation of the branch, but supports comparison and other ROOT-like functionality.

Working example [on CERN gitlab here](https://gitlab.cern.ch/hschrein/roottools/blob/master/python/roopy.py). Ignore everything besides TextTree and TextBranch.

**Comment by ndawe** [comment]
This would be a nice contribution to rootpy. I like that you have directly subclassed str.  I guess we just need a simple property like ``b`` here and one that isn't likely to conflict with branch names since in rootpy you can access the current branch value with ``tree.branchname``.

**Comment by ndawe** [comment]
Closing this now as this feature has been merged in. Thanks again!
