### ISSUE TITLE
tree2array only one column

### ISSUE THREAD

**Issue by AFanthomme** [rootpy/rootpy#738]
Hi,
Not sure if bug or intended feature, but it might be confusing that tree2array sometimes returns a numpy array but with only one column, where it would be pretty legitimate to expect as many columns as retrieved branches.
At least it could be mentioned in the documentation to avoid unnecessary debugging.

**Comment by nasfarley88** [comment]
Do you have a code example of where this happens?

**Comment by AFanthomme** [comment]
Here is what I used to test 

def test():
    file_vbf =  # the name of my file
    kin_variables_list = ['nExtraLep', 'nExtraZ', 'nCleanedJetsPt30']

    vbf_rfile = r.TFile(file_vbf)
    vbf_tree = vbf_rfile.Get('MyTree')
    vbf_array = tree2array(vbf_tree, branches=kin_variables_list, stop=5)
    print(np.shape(vbf_array))
    print(vbf_array[0])

The shape is (nb_events,) and the second print outputs the 5 features that I tried to extract.

**Comment by ndawe** [comment]
@AFanthomme this issue belongs on the root_numpy issue tracker: https://github.com/scikit-hep/root_numpy/issues but we can continue here. No worries.

tree2array gives you a structured array aka record array. Each element of the array is a tuple of field values. This is why the shape is (nb_events,). The elements of the array are the record tuples and the number of things within each record is not included in the shape of the array.

You can access arrays of each field with ``vbf_array['nExtraLep']`` etc.

**Comment by ndawe** [comment]
This numpy documentation might also help:

https://docs.scipy.org/doc/numpy/user/basics.rec.html

**Comment by AFanthomme** [comment]
Oh okay that's what was meant by structured array, all apologies.
Maybe it wouldn't hurt to put your remark as a note in the documentation though, just for the sake of clarity

Thanks anyways !
