### ISSUE TITLE
Bin labels are lost with `rootpy.plotting.util.draw`

### ISSUE THREAD

**Issue by annawoodard** [rootpy/rootpy#744]
The [documentation](https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/utils.py#L49) of `rootpy.plotting.util.draw` indicates that if you do not specify axes, the axes of the first plottable will be used. But [here](https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/utils.py#L110) a temporary histo is created, so any bin labels that were set in the first plottable are lost. For example:

```
import rootpy
from rootpy.plotting import Hist
from rootpy.plotting.utils import draw

h = Hist(10, 0., 10.)
h.Fill(2.)
for i in range(10):
    h.xaxis.SetBinLabel(i + 1, 'bin {}'.format(i + 1))

draw(h)
```

Why not just use the first plottable? I've implemented it [here](https://github.com/annawoodard/rootpy/commit/6c2b77dd2cd8539478c67367d088c6872123835b) but wanted to document the issue first (because maybe I'm missing something obvious) before opening a PR.

**Comment by ndawe** [comment]
Thanks for fixing that. You're right. I don't know why I didn't have it taking the first plottable like the docs say. Can you open a PR with your fix?

**Comment by annawoodard** [comment]
Sure thing!
