### ISSUE TITLE
Profile vs Hist

### ISSUE THREAD

**Issue by JOliver-GH** [rootpy/rootpy#753]
Hi Noel, 

I have 2 variables, a "p_{t}" and a clustersize.
pt in this case is a complicated mess like "InDetTrackParticles..InDetTrackParticles.qOverp * InDetTrackParticles..InDetTrackParticles.theta" and clustersize is stored as "SCT_ClustersAuxDyn..SCT_ClustersAuxDyn.SiWidth"

 I want to plot this as "x:y", or "pt:clustersize" but I want the value of the y axis to be the mean of the clustersize, for a given rms / bin of pt. 

I'm aware that this is the use of the Profile class, my difficulty has been figuring out how to implement this in the rootpy sense 

I've looked @ the class definition, and the documentation, but i haven't been able to figure out how to achieve my goal,

i think the following should work, but I either get an unmodified plot, or an empty plot

profilex = tree.Draw("pt:clustersize >> Profile(70,0,70000)",selection='1',drawstyle='hist') 
profilex.Draw()

Is there something obvious I'm missing or is there a snippet of code you have to show me how this can be written in a code? 

Cheers

**Comment by ndawe** [comment]
Probably best to read the docs for TTree:Draw here: https://root.cern.ch/doc/master/classTTree.html#a73450649dc6e54b5b94516c468523e45

"pt:clustersize >> Profile(70,0,70000)" isn't valid unless you already have a TProfile (or rootpy Profile) named Profile. Or you can create a profile first and then use Draw's hist= argument to specify that you want to fill that specific profile.
