### ISSUE TITLE
`Efficiency.__iadd__` is broken

### ISSUE THREAD

**Issue by benkrikler** [rootpy/rootpy#762]
I think the implementation of iadd for rootpy.plotting.Efficiency might be broken.
The culprit line is https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/hist.py#L2562.

I think the fix is very straightforward though:
```py
super(Efficiency, self).Add(other)
```
ie. remove the `self` argument in `Add()`.

**Comment by ndawe** [comment]
Good catch. You're right. Fixing that now

**Comment by ndawe** [comment]
Fixed in #763
