### ISSUE TITLE
Typo in pdg_table.txt 

### ISSUE THREAD

**Issue by yschutz** [rootpy/rootpy#764]
441 D*_1s+            20433  1 100 Unknown     3 2.4596e+00 5.50000e-03 -100 -1 -100 -1   -1   2
#----------------------------------------------------------------------
#    decay  type(PY6)    BR     Nd         daughters(codes, then names)
#----------------------------------------------------------------------
         1     0   8.00000e-01   2      433      111                                     D*_s+      pi0
         1     0   2.00000e-01   2      433       22                                     D*_s+      gamma

should be
  441 D*_1s+            20433  1 100 Unknown     3 2.4596e+00 5.50000e-03 -100 -1 -100 -1   -1   2
#----------------------------------------------------------------------
#    decay  type(PY6)    BR     Nd         daughters(codes, then names)
#----------------------------------------------------------------------
         1     0   8.00000e-01   2      433      111                                     D*_s+      pi0
         2     0   2.00000e-01   2      433       22                                     D*_s+      gamma: <<=========

**Comment by ndawe** [comment]
This file is taken directly from ROOT's etc/pdg_table.txt. Can you report the typo there first?

https://sft.its.cern.ch/jira/projects/ROOT
