### ISSUE TITLE
Histogram drawstyle isn't saved when writing to a .root file

### ISSUE THREAD

**Issue by H4rtland** [rootpy/rootpy#779]
This is the script I'm running

```python
import math

import rootpy
import rootpy.io
import rootpy.plotting
from rootpy.plotting.style import get_style
from rootpy.interactive import wait


with rootpy.io.root_open("z_mass.root", "recreate") as root_file:
    z_mass_hist = rootpy.plotting.Hist(50, 50, 150,
                            name="z_mass", title="Z Mass", type="D", drawstyle="hist")
    z_mass_more_bins = rootpy.plotting.Hist(100, 50, 150,
                            name="z_mass_bins", title="Z mass", type="D", drawstyle="hist")

    z_mass_hist.linecolor = 602 # "blue"
    z_mass_hist.drawstyle = "hist"
    
    with open("z.dat", "r") as data_file:
        with open("z.out", "w") as output_file:
            for line in data_file.readlines():
                if len(line.strip()) == 0: break
                
                data = map(float, line.split("\t"))
                
                p1, e1, p2, e2 = data[0:3], data[3], data[4:7], data[7]
                
                ez = e1 + e2
                pz = [a+b for a, b in zip(p1, p2)]
                
                mz = math.sqrt(reduce(lambda x, y: x-y**2, pz, ez**2))
                
                z_mass_hist.fill(mz)
                z_mass_more_bins.fill(mz)
                
                output_file.write("{0}\n".format(mz))

    z_mass_hist.draw()
    wait()
    z_mass_hist.write()
```

I set `drawstyle = "hist"` both in the initialization and one time after.

When I open the z_mass histogram from z_mass.root after it's been saved and closed, it looks completely different to how it does when it's shown with z_mass_hist.draw() near the end of the above script. The reason is, hist.drawstyle has reverted to an empty string.

Video demonstration https://streamable.com/fgg7u

I've only been using ROOT for a week or so, rootpy for even less time, so I'm not sure where to start looking for the cause of this.

ROOT 5.34/32
rootpy 1.0.1
python 2.6.6

**Comment by H4rtland** [comment]
ROOT 5.34/32
rootpy 1.0.1
python 2.6.6

**Comment by H4rtland** [comment]
Although now that I've tried looking at the same histogram but produced by C++ ROOT, drawstyle is an empty string but it does display as a proper histogram. I tried messing with line styles, fill styles etc while I was trying to get rootpy to work earlier, but I couldn't get rid of the scatter plot looking style. Is there just some combination of options that I'm missing?

**Comment by ndawe** [comment]
drawstyle is an attribute added by rootpy and is not mirrored on the C++ side, so is not saved in a ROOT file

**Comment by H4rtland** [comment]
Ah, thanks for clearing that up for me.

What's the method for permanently storing the histogram style in a .root file then? The [c++ I'm translating from](https://github.com/H4rtland/masters/blob/master/week1/z_read_root.cpp) doesn't specify any styling options. PyROOT doesn't need anything specific to look right either. What is drawstyle doing in rootpy that doesn't need to be done in c++/PyROOT?

**Comment by ndawe** [comment]
Any of the TAttLine, TAttMarker, TAttFill attributes will be saved with the histogram, as usual in ROOT, but ROOT's draw mode (the awkward string used to specify how the object is drawn) is not. You could use rootpy.io.pickler to save a pickle of the drawstyle in the ROOT file along with your histogram. That's one option. http://www.rootpy.org/reference/io.pickler.html

**Comment by H4rtland** [comment]
I'll give that a try, thanks.
