### ISSUE TITLE
Errors when installing with latest recommended ROOT

### ISSUE THREAD

**Issue by saptajihva** [rootpy/rootpy#796]
Hi,

I'm getting some errors when I run rootpy that was installed with root 6.14.04-x86_64-slc6-gcc62-opt (in the ATLAS environment) that I can't make sense of.

When doing a user install I see the following warnings/messages:

> rootpy.decorators: module references \_\_file\_\_
rootpy.extern.pyparsing: module MAY be using inspect.stack
rootpy.extern.six: module references \_\_path\_\_
rootpy.utils.module_facade: module references \_\_file\_\_
rootpy.utils.tests.test_ext_glob: module references \_\_file\_\_

Then when running I get the following:
>Traceback (most recent call last):
  File "source/rootpyPlotter.py", line 16, in <module>
    from rootpy.plotting import F1, Hist, HistStack, Canvas, Legend, Pad
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/ROOT/6.14.04/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/assharma/.local/lib/python2.7/site-packages/rootpy-1.0.0.dev0-py2.7.egg/rootpy/plotting/__init__.py", line 11, in <module>
    from .func import F1, F2, F3
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/ROOT/6.14.04/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/assharma/.local/lib/python2.7/site-packages/rootpy-1.0.0.dev0-py2.7.egg/rootpy/plotting/func.py", line 7, in <module>
    import six
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_94/ROOT/6.14.04/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named six

I tried removing everything and installing with version 6.10.06 of ROOT but I get the same kind of errors when I try to run. I guess this is a compatibility issue between versions of rootpy and ROOT, but I don't know what the recipe should be. Unfortunately I can't run any of the usual tests as I am on our cluster.

Any help would be much appreciated!

Thanks,

Abhishek

**Comment by rakab** [comment]
Hi,

> When doing a user install I see the following warnings/messages:
> 
> rootpy.decorators: module references __file__
> rootpy.extern.pyparsing: module MAY be using inspect.stack
> rootpy.extern.six: module references __path__
> rootpy.utils.module_facade: module references __file__
> rootpy.utils.tests.test_ext_glob: module references __file__

Errors like this usually come  when using ```easy_install``` for installing the package. I guess, it's what you are doing for installing rootpy, right?

The recommended way to install rootpy is with pip:
```bash
pip install rootpy --user
```
I'm using ATLAS environment as well, with same exact root 6.14.04-x86_64-slc6-gcc62-opt version  and  with default python version, which comes with root 6.14.04 everything works fine. Let me know if you need further assistance.

Cheers,
Bakar

**Comment by saptajihva** [comment]
Thanks a lot Bakar, it worked using pip!

Just in case anyone else has a similar issue, I had to install a newer user version of pip to play nicely with ROOT in our environment. 

>curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
>python get-pip.py --user

Cheers,

Abhishek
