### ISSUE TITLE
Fill an STL vector of vectors

### ISSUE THREAD

**Issue by gipert** [rootpy/rootpy#801]
How do I push-back new elements in a `stl.vector(stl.vector('double'))`? If I try something like `v.push_back(std.vector('double'))` it complains that
```
push_back must be called with a vector<vector<double> > instance as first argument
```
which confuses me a bit...

**Comment by gipert** [comment]
Am I wrong or all this is a consequence of the new `cppyy` approach?

**Comment by rakab** [comment]
Hi,

your vector should be instantiated before pushing new elements into it.
This is a working example:
```python
from rootpy.stl import vector

V = vector('double')
v=V()
v.push_back(10)
v.push_back(-27.5)

print(list(v))
```

More examples can be seen here:
http://www.rootpy.org/reference/stl.html

Cheers,
Bakar

**Comment by gipert** [comment]
That did the job, thank you.
