### ISSUE TITLE
root errors turn always in python exceptions

### ISSUE THREAD

**Issue by greyxray** [rootpy/rootpy#802]
I have run the [example](http://www.rootpy.org/reference/logger.html) with Python 2.7.15 from `/cvmfs/sft.cern.ch/lcg/views/LCG_94/x86_64-slc6-gcc62-opt/bin/python` and root 6.14 (`/cvmfs/sft.cern.ch/lcg/views/LCG_94/x86_64-slc6-gcc62-opt/bin/root`) but with setting the `DANGER.enable = False` the ROOT errors are still rising python exceptions. I assume this is not the intended behaviour? The corresponding log part:
```
ERROR:ROOT.test] Test fatal
Traceback (most recent call last):
  File "tests/root_errors.py", line 41, in <module>
    ROOT.Error("test", "Test fatal")
  File "tests/root_errors.py", line 41, in <module>
    ROOT.Error("test", "Test fatal")
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_94/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/rootpy/logger/magic.py", line 245, in intercept_next_line
    raise exception
```
Is there another way to use the logger (for nice outputs) but without rising the python exception?

**Comment by rakab** [comment]
There is an typo-like error in documentation.
Instead of :
```python
DANGER.enable = False
```
It should be:
```python
DANGER.enabled = False
````
enable ->enable**d**

That should fix your issue.

Cheers,
Bakar
