### ISSUE TITLE
rootpy.org no longer available

### ISSUE THREAD

**Issue by kreczko** [rootpy/rootpy#807]
```
NOTICE: This domain name expired on 7/11/2019 and is pending renewal or deletion.
```

Are there plans to move to a free alternative (e.g. readthedocs.org)?

**Comment by ndawe** [comment]
Yikes! My bad. I'll renew for another year and we can transition to readthedocs.org

**Comment by ndawe** [comment]
It's renewed and should be working again in 1 to 2 days

**Comment by ndawe** [comment]
... and we're live again :)

**Comment by kreczko** [comment]
Awesome! Thank you very much :)
