### ISSUE TITLE
Change cache location?

### ISSUE THREAD

**Issue by tomeichlersmith** [rootpy/rootpy#818]
Hello rootpy community!

I am working with a collaboration that uses a container to distribute our computing environment, and we are trying to include rootpy for our users. Is there a way for me to change the location of the `.cache` directory? In the container, the `$HOME` variable is empty, so the `.cache` directory ends up in `/` which is inaccessible by the user.

Right now, before importing rootpy, I am trying to change the home directory to something that is accessible by the user, e.g.
```python
os.environ["HOME"] = "<path-to-accessible-directory>"
```

Is this the best way? Or is there a way for me to change the location when I install rootpy on the container so the users don't have to add the above lines to their scripts.

**Comment by ndawe** [comment]
Hi @tomeichlersmith, I think the best way would be to set the following variables to an alternate path:

```
XDG_CONFIG_HOME
XDG_CACHE_HOME
```

they default to `~/.config` and `~/.cache` respectively.

Refer to the code here:

https://github.com/rootpy/rootpy/blob/master/rootpy/userdata.py#L24

```
if "XDG_CONFIG_HOME" not in os.environ:
    os.environ["XDG_CONFIG_HOME"] = expanduser('~/.config')
if "XDG_CACHE_HOME" not in os.environ:
    os.environ["XDG_CACHE_HOME"] = expanduser('~/.cache')
```

**Comment by tomeichlersmith** [comment]
Thank you! This worked :+1:
